diff --git a/docker-compose.yml b/docker-compose.yml
new file mode 100644
index 0000000000000000000000000000000000000000..b6e16b86150c1fe27a32e16e1adcc4c1375c2db1
--- /dev/null
+++ b/docker-compose.yml
@@ -0,0 +1,24 @@
+version: '3.9'
+services:
+  redis:
+    image: redis:7-alpine
+    ports:
+      - '6379:6379'
+
+  api:
+    build: .
+    command: npm run start:api
+    env_file:
+      - .env
+    depends_on:
+      - redis
+    ports:
+      - '3000:3000'
+
+  worker:
+    build: .
+    command: npm run start:worker
+    env_file:
+      - .env
+    depends_on:
+      - redis
